// ============================================================
// Shared types for the AI Video Summarizer backend
// ============================================================

/** The four output formats a user can request */
export type OutputType = 'summary' | 'flashcards' | 'keyPoints' | 'highlights';

export const ALL_OUTPUT_TYPES: OutputType[] = [
  'summary',
  'flashcards',
  'keyPoints',
  'highlights',
];

/** How the video was supplied */
export type InputSource = 'file' | 'url';

/** Processing stages surfaced to the frontend */
export type JobStage =
  | 'queued'
  | 'uploading'
  | 'extracting'
  | 'analyzing'
  | 'generating'
  | 'completed'
  | 'failed';

export interface SectionBreakdownItem {
  title: string;
  content: string;
}

export interface SummaryResult {
  executiveSummary: string;
  detailedSummary: string;
  sectionBreakdown: SectionBreakdownItem[];
  conclusion: string;
}

export interface FlashcardItem {
  question: string;
  answer: string;
}

export type HighlightType = 'moment' | 'takeaway' | 'statement' | 'insight';

export interface HighlightItem {
  type: HighlightType;
  title: string;
  description: string;
  timestamp?: string;
}

/** The full structured response generated by Gemini */
export interface VideoAnalysisResult {
  videoTitle?: string;
  summary?: SummaryResult;
  flashcards?: FlashcardItem[];
  keyPoints?: string[];
  highlights?: HighlightItem[];
}

export interface Job {
  id: string;
  status: JobStage;
  progress: number; // 0-100
  message: string;
  result?: VideoAnalysisResult;
  error?: string;
  createdAt: number;
  updatedAt: number;
  fromCache?: boolean;
  /** Reference to the video as understood by Gemini, kept alive for chat follow-ups */
  videoRef?: VideoReference;
}

export interface ProcessVideoRequestBody {
  outputs: OutputType[];
  url?: string;
}

/** A reference to a video already known to Gemini (uploaded file or YouTube URL) */
export interface VideoReference {
  fileUri: string;
  mimeType: string;
  /** Gemini Files API resource name (only set for uploaded files, not YouTube URLs) */
  geminiFileName?: string;
}

export type ChatRole = 'user' | 'model';

export interface ChatMessage {
  role: ChatRole;
  text: string;
}

export interface ChatRequestBody {
  jobId: string;
  question: string;
  /** Prior turns of the conversation, oldest first (excludes the new question) */
  history?: ChatMessage[];
}

export interface ChatResponseBody {
  answer: string;
}
